/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.ResourceBundle;

/**
 *
 * @author Carlos
 */
public class BuscarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Read
     */
     private ControladorCliente controladorcliente;
      private ResourceBundle mensajes;
     
     
    public BuscarCliente(ControladorCliente ControladorCliente,ResourceBundle mensaje) {
        initComponents();
        this.controladorcliente = ControladorCliente;
         this.mensajes = mensaje;
       cambiarIdioma(mensaje);
    }
    
    public void cambiarIdioma(ResourceBundle mensajes) {
        LN.setText(mensajes.getString("cliente.nombre"));
        LC.setText(mensajes.getString("cliente.codigo"));
        
        LCE.setText(mensajes.getString("cliente.cedula"));
        LD.setText(mensajes.getString("cliente.direccion"));
        LT.setText(mensajes.getString("cliente.telefono"));
        cancelar.setText(mensajes.getString("boton.cancelar"));
        buscar.setText(mensajes.getString("boton.buscar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LC = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        LT = new javax.swing.JLabel();
        LD = new javax.swing.JLabel();
        LN = new javax.swing.JLabel();
        LCE = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(102, 255, 102));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LC.setText("CODIGO:");
        jPanel2.add(LC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 130, 30));

        buscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 240, 40));

        txtcodigo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 170, 40));

        txtnombre.setEditable(false);
        txtnombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 250, 50));

        txtcedula.setEditable(false);
        txtcedula.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 250, 50));

        txttelefono.setEditable(false);
        txttelefono.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 250, 50));

        txtdireccion.setEditable(false);
        txtdireccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 250, 60));

        LT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LT.setText("TELEFONO:");
        jPanel2.add(LT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, 30));

        LD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LD.setText("DIRECCION:");
        jPanel2.add(LD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 160, 30));

        LN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LN.setText("NOMBRE:");
        jPanel2.add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, 30));

        LCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LCE.setText("CEDULA:");
        LCE.setToolTipText("");
        jPanel2.add(LCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 120, 30));

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 255, 204));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        int codigo=Integer.parseInt(txtcodigo.getText());
        Cliente cliente = controladorcliente.read(codigo);
        System.out.println(cliente);
        txtnombre.setText(cliente.getNombre());
        txtcedula.setText(cliente.getCedula());
        txtdireccion.setText(cliente.getDireccion());
        txttelefono.setText(cliente.getTelefono());
    }//GEN-LAST:event_buscarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LC;
    private javax.swing.JLabel LCE;
    private javax.swing.JLabel LD;
    private javax.swing.JLabel LN;
    private javax.swing.JLabel LT;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
