/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class CrearCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaSecundaria
     */
    private ControladorCliente controladorcliente;
    private ResourceBundle mensajes;
    
    public CrearCliente(ControladorCliente ControladorCliente, ResourceBundle mensajes) {
        initComponents();
        this.controladorcliente = ControladorCliente;
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        
        LCODIGO.setText(mensajes.getString("cliente.codigo"));
        JN.setText(mensajes.getString("cliente.nombre"));
        JCE.setText(mensajes.getString("cliente.cedula"));
        JD.setText(mensajes.getString("cliente.direccion"));
        JT.setText(mensajes.getString("cliente.telefono"));
        Aceptar.setText(mensajes.getString("boton.crear"));
        cancelar.setText(mensajes.getString("boton.cancelar"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JCE = new javax.swing.JLabel();
        LCODIGO = new javax.swing.JLabel();
        JD = new javax.swing.JLabel();
        JT = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        txtcodigo = new javax.swing.JTextField();
        JN = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Crear Cliente\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 255, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JCE.setText("CEDULA:");
        JCE.setToolTipText("");
        jPanel1.add(JCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 30));

        LCODIGO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LCODIGO.setText("CODIGO:");
        jPanel1.add(LCODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 30));

        JD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JD.setText("DIRECCION:");
        jPanel1.add(JD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 30));

        JT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT.setText("TELEFONO:");
        jPanel1.add(JT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 30));

        txtcedula.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 220, 50));

        txttelefono.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 220, 50));

        txtnombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 220, 50));

        txtdireccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 220, 50));

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 255, 204));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 150, 40));

        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(0, 255, 204));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 150, 40));

        txtcodigo.setEditable(false);
        txtcodigo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 220, 50));

        JN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JN.setText("NOMBRE:");
        jPanel1.add(JN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));
        jPanel1.getAccessibleContext().setAccessibleName("Crear clietne");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setNombre(txtnombre.getText());
        cliente.setCedula(txtcedula.getText());
        cliente.setDireccion(txtdireccion.getText());
        cliente.setTelefono(txttelefono.getText());
        controladorcliente.create(cliente);
        JOptionPane.showMessageDialog(this, "Cliente creado exitosamente!!", "Crear Cliente", JOptionPane.OK_OPTION);
        ////////limpiar
        txtnombre.setText("");
        txtcedula.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcodigo.setText(String.valueOf(this.controladorcliente.getCodigo()));
    }//GEN-LAST:event_AceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel JCE;
    private javax.swing.JLabel JD;
    private javax.swing.JLabel JN;
    private javax.swing.JLabel JT;
    private javax.swing.JLabel LCODIGO;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
