/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;
import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */

public class EliminarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Delate
     */
     private ControladorCliente controladorcliente;
      private ResourceBundle mensajes;
      
    public EliminarCliente(ControladorCliente ControladorCliente, ResourceBundle mensaje) {
        initComponents();
         this.controladorcliente = ControladorCliente;
          this.mensajes = mensaje;
        cambiarIdioma(mensaje);
    }
    public void cambiarIdioma(ResourceBundle mensajes) {
        LN.setText(mensajes.getString("cliente.nombre"));
        LC.setText(mensajes.getString("cliente.codigo"));
        
        LCE.setText(mensajes.getString("cliente.cedula"));
        LD.setText(mensajes.getString("cliente.direccion"));
        LT.setText(mensajes.getString("cliente.telefono"));
        cancelar.setText(mensajes.getString("boton.cancelar"));
        buscar.setText(mensajes.getString("boton.buscar"));
        BE.setText(mensajes.getString("boton.eliminar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LC = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        LN = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        LCE = new javax.swing.JLabel();
        LD = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        LT = new javax.swing.JLabel();
        BE = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 0));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LC.setText("CODIGO:");
        jPanel1.add(LC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 200, 30));

        txtcodigo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 170, 40));

        buscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 240, 40));

        LN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LN.setText("NOMBRE:");
        jPanel1.add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 120, 30));

        txtnombre.setEditable(false);
        txtnombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 250, 50));

        txtcedula.setEditable(false);
        txtcedula.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 250, 50));

        LCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LCE.setText("CEDULA:");
        LCE.setToolTipText("");
        jPanel1.add(LCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 120, 30));

        LD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LD.setText("DIRECCION:");
        jPanel1.add(LD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 30));

        txtdireccion.setEditable(false);
        txtdireccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 250, 60));

        txttelefono.setEditable(false);
        txttelefono.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 250, 50));

        LT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LT.setText("TELEFONO:");
        jPanel1.add(LT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 160, 30));

        BE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BE.setForeground(new java.awt.Color(153, 255, 102));
        BE.setText("ELIMINAR");
        BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEActionPerformed(evt);
            }
        });
        jPanel1.add(BE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 136, 40));

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 255, 204));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        int codigo=Integer.parseInt(txtcodigo.getText());
        Cliente cliente = controladorcliente.read(codigo);
        System.out.println(cliente);
        txtnombre.setText(cliente.getNombre());
        txtcedula.setText(cliente.getCedula());
        txtdireccion.setText(cliente.getDireccion());
        txttelefono.setText(cliente.getTelefono());
    }//GEN-LAST:event_buscarActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtcodigo.getText());
        controladorcliente.delete(codigo);
        JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente!!", "Crear cliente" , JOptionPane.OK_OPTION);
        txtcodigo.setText("");
        txtcedula.setText("");
        txtnombre.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
    }//GEN-LAST:event_BEActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BE;
    private javax.swing.JLabel LC;
    private javax.swing.JLabel LCE;
    private javax.swing.JLabel LD;
    private javax.swing.JLabel LN;
    private javax.swing.JLabel LT;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
