/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.controladores.ControladorProducto;
import ec.edu.ups.controladores.ControladorFactura;
import ec.edu.ups.controladores.ControladorFacturaDetalle;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Producto;
import java.util.Locale;
import java.util.ResourceBundle;
/**
 *
 * @author Carlos
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private ControladorCliente controladorcliente;
private ControladorFactura controladorfactura;
private ControladorProducto controladorproducto;
private ControladorFacturaDetalle controladorfacturadetalle;
 private Locale localizacion;
    private ResourceBundle mensajes;
//Cliente
    private CrearCliente crearCliente;
    private BuscarCliente readCliente;
    private ModificarCliente updateCliente;
    private EliminarCliente deleteCliente;
    private ListaCliente listarClientes;

  

    //Producto
    private CrearProducto crearProducto;
    private BuscarProducto readProducto;
    private ModificarProducto updateProducto;
    private EliminarProducto deleteProducto;
    private ListaProducto listarProducto;
    
     //Factura
    private CrearFactura crearFactura;
    /**private BuscarFactura readFactura;
    private ModificarFactura updateFactura;
    private EliminarFactura deleteFactura;
    private ListarFactura listarFacturas;
*/

    /**
     * Creates new form Ventana
     */
    public VentanaPrincipal() {
        initComponents();
        controladorcliente = new ControladorCliente();
     controladorproducto = new ControladorProducto();
        controladorfactura = new ControladorFactura();
         
        localizacion = new Locale("es","EC");
        Locale.setDefault(localizacion);
         cambiarIdioma();
    }
public void cambiarIdioma(){
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        
        C.setText(mensajes.getString("menu.cliente"));
        
        CC.setText(mensajes.getString("menu.item.crear"));
        CB.setText(mensajes.getString("menu.item.buscar"));
        CM.setText(mensajes.getString("menu.item.modificar"));
        CE.setText(mensajes.getString("menu.item.eliminar"));
        CL.setText(mensajes.getString("menu.item.lista"));
        
        P.setText(mensajes.getString("menu.producto"));
        
        PC.setText(mensajes.getString("menu.item.crear"));
        PB.setText(mensajes.getString("menu.item.buscar"));
        PM.setText(mensajes.getString("menu.item.modificar"));
        PE.setText(mensajes.getString("menu.item.eliminar"));
        PL.setText(mensajes.getString("menu.item.lista"));
        
        F.setText(mensajes.getString("menu.Factura"));
        
        FC.setText(mensajes.getString("menu.item.crear"));
       /* F.setText(mensajes.getString("menu.item.buscar"));
        modificarproducto.setText(mensajes.getString("menu.item.modificar"));
        eliminarproducto.setText(mensajes.getString("menu.item.eliminar"));
        listarproducto.setText(mensajes.getString("menu.item.lista"));
        */
        I.setText(mensajes.getString("menu.idioma"));
        II.setText(mensajes.getString("menu.item.ingles"));
        IE.setText(mensajes.getString("menu.item.espa"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        C = new javax.swing.JMenu();
        CC = new javax.swing.JMenuItem();
        CB = new javax.swing.JMenuItem();
        CM = new javax.swing.JMenuItem();
        CE = new javax.swing.JMenuItem();
        CL = new javax.swing.JMenuItem();
        P = new javax.swing.JMenu();
        PC = new javax.swing.JMenuItem();
        PB = new javax.swing.JMenuItem();
        PM = new javax.swing.JMenuItem();
        PE = new javax.swing.JMenuItem();
        PL = new javax.swing.JMenuItem();
        F = new javax.swing.JMenu();
        FC = new javax.swing.JMenuItem();
        I = new javax.swing.JMenu();
        II = new javax.swing.JMenuItem();
        IE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 697, 486));

        C.setMnemonic('f');
        C.setText("Cliente");

        CC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CC.setMnemonic('o');
        CC.setText("Crear");
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });
        C.add(CC);

        CB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        CB.setMnemonic('s');
        CB.setText("Buscar");
        CB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBMouseClicked(evt);
            }
        });
        CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBActionPerformed(evt);
            }
        });
        C.add(CB);

        CM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        CM.setMnemonic('a');
        CM.setText("Modificar");
        CM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMActionPerformed(evt);
            }
        });
        C.add(CM);

        CE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        CE.setMnemonic('x');
        CE.setText("Eliminar");
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });
        C.add(CE);

        CL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        CL.setMnemonic('x');
        CL.setText("Lista");
        CL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLActionPerformed(evt);
            }
        });
        C.add(CL);

        menu.add(C);

        P.setMnemonic('f');
        P.setText("Producto");

        PC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        PC.setMnemonic('o');
        PC.setText("Crear");
        PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCActionPerformed(evt);
            }
        });
        P.add(PC);

        PB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        PB.setMnemonic('s');
        PB.setText("Buscar");
        PB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PBMouseClicked(evt);
            }
        });
        PB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBActionPerformed(evt);
            }
        });
        P.add(PB);

        PM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        PM.setMnemonic('a');
        PM.setText("Modificar");
        PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMActionPerformed(evt);
            }
        });
        P.add(PM);

        PE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        PE.setMnemonic('x');
        PE.setText("Eliminar");
        PE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEActionPerformed(evt);
            }
        });
        P.add(PE);

        PL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        PL.setMnemonic('x');
        PL.setText("Lista");
        PL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLActionPerformed(evt);
            }
        });
        P.add(PL);

        menu.add(P);

        F.setMnemonic('f');
        F.setText("Factura");

        FC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        FC.setMnemonic('o');
        FC.setText("Crear");
        FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCActionPerformed(evt);
            }
        });
        F.add(FC);

        menu.add(F);

        I.setMnemonic('e');
        I.setText("Idioma");

        II.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        II.setMnemonic('t');
        II.setText("Ingles");
        II.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IIActionPerformed(evt);
            }
        });
        I.add(II);

        IE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        IE.setMnemonic('y');
        IE.setText("Español");
        IE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IEActionPerformed(evt);
            }
        });
        I.add(IE);

        menu.add(I);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
      
         EliminarCliente crear = new EliminarCliente(controladorcliente,mensajes);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_CEActionPerformed

    private void CLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLActionPerformed
        // TODO add your handling code here:
        ListaCliente crear = new ListaCliente(controladorcliente,mensajes   );
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_CLActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        // TODO add your handling code here:
       CrearCliente crear = new CrearCliente(controladorcliente ,mensajes);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_CCActionPerformed

    private void CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBActionPerformed
        // TODO add your handling code here:
        BuscarCliente  buscar =new BuscarCliente(controladorcliente,mensajes);
        buscar.setVisible(true);
        desktopPane.add(buscar);
    }//GEN-LAST:event_CBActionPerformed

    private void CBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMouseClicked

    private void CMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMActionPerformed
        // TODO add your handling code here:
        ModificarCliente  buscar =new ModificarCliente(controladorcliente,mensajes);
        buscar.setVisible(true);
        desktopPane.add(buscar);
    }//GEN-LAST:event_CMActionPerformed

    private void PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCActionPerformed
        // TODO add your handling code here:
       if (crearProducto== null || crearProducto.isVisible() == false) {
            crearProducto = new CrearProducto(controladorproducto, mensajes);
            crearProducto.setVisible(true);
            desktopPane.add(crearProducto);
        }
    }//GEN-LAST:event_PCActionPerformed

    private void PBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PBMouseClicked
        // TODO add your handling code here:
         BuscarProducto crear = new BuscarProducto(controladorproducto);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_PBMouseClicked

    private void PBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBActionPerformed
        // TODO add your handling code here:
        BuscarProducto crear = new BuscarProducto(controladorproducto);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_PBActionPerformed

    private void PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMActionPerformed
        // TODO add your handling code here:
    ModificarProducto crear = new ModificarProducto(controladorproducto);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_PMActionPerformed

    private void PEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEActionPerformed
        // TODO add your handling code here:
         EliminarProducto crear = new EliminarProducto(controladorproducto);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_PEActionPerformed

    private void PLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLActionPerformed
        // TODO add your handling code here:
     ListaProducto crear = new ListaProducto(controladorproducto);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_PLActionPerformed

    private void FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCActionPerformed
        // TODO add your handling code here:
        CrearFactura crear = new CrearFactura(controladorfactura, controladorfacturadetalle, controladorcliente, controladorproducto);
      crear.setVisible(true);
      desktopPane.add(crear);
    }//GEN-LAST:event_FCActionPerformed

    private void IIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IIActionPerformed
        // TODO add your handling code here:
       localizacion = new Locale("en","US");
        Locale.setDefault(localizacion);
        cambiarIdioma();
        System.out.println("Localizacion Forzada: "+Locale.getDefault().getLanguage());
    }//GEN-LAST:event_IIActionPerformed

    private void IEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IEActionPerformed
        // TODO add your handling code here:
         localizacion = new Locale("es","EC");
        Locale.setDefault(localizacion);
        cambiarIdioma();
        System.out.println("Localizacion Forzada: "+Locale.getDefault().getLanguage());
    }//GEN-LAST:event_IEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu C;
    private javax.swing.JMenuItem CB;
    private javax.swing.JMenuItem CC;
    private javax.swing.JMenuItem CE;
    private javax.swing.JMenuItem CL;
    private javax.swing.JMenuItem CM;
    private javax.swing.JMenu F;
    private javax.swing.JMenuItem FC;
    private javax.swing.JMenu I;
    private javax.swing.JMenuItem IE;
    private javax.swing.JMenuItem II;
    private javax.swing.JMenu P;
    private javax.swing.JMenuItem PB;
    private javax.swing.JMenuItem PC;
    private javax.swing.JMenuItem PE;
    private javax.swing.JMenuItem PL;
    private javax.swing.JMenuItem PM;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables

}
